apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deploy
  labels:
    app: rails-web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rails-web-app
  template:
    metadata:
      labels:
        app: rails-web-app
    spec:
      containers:
      - name: rails-app
        image: shreyansh0770/rails-app:latest
        env:
        - name: DB_HOST
          value: "postgres"
        - name: DB_USER
          value: "shreyansh"
        - name: DB_PASSWORD
          value: "123456789"
        - name: DB_NAME
          value: "rails_dev"
        ports:
        - containerPort: 3000
